set(ASMJIT_NO_INSTALL ON CACHE BOOL "" FORCE)
set(ASMTK_NO_INSTALL ON CACHE BOOL "" FORCE)
set(ASMJIT_STATIC ON CACHE BOOL "" FORCE)
set(ASMJIT_NO_AARCH64 ON CACHE BOOL "" FORCE)
set(ASMJIT_NO_JIT ON CACHE BOOL "" FORCE)
set(ASMJIT_NO_COMPILER ON CACHE BOOL "" FORCE)
set(ASMJIT_NO_UJIT ON CACHE BOOL "" FORCE)
set(ASMJIT_NO_BUILDER ON CACHE BOOL "" FORCE)
set(ASMJIT_NO_NATVIS ON CACHE BOOL "" FORCE)
set(ASMTK_STATIC ON CACHE BOOL "" FORCE)
set(ASMTK_TEST OFF CACHE BOOL "" FORCE)
set(ASMJIT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/third_party/asmjit" CACHE PATH "" FORCE)
add_subdirectory(third_party/asmtk EXCLUDE_FROM_ALL)
set(ZYDIS_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(ZYDIS_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(ZYDIS_BUILD_DOXYGEN OFF CACHE BOOL "" FORCE)
set(ZYDIS_FEATURE_ENCODER OFF CACHE BOOL "" FORCE)
set(ZYDIS_FEATURE_FORMATTER OFF CACHE BOOL "" FORCE)
add_subdirectory(third_party/zydis EXCLUDE_FROM_ALL)
add_library(patch_compiler STATIC src/patch_definitions.cpp src/patch_package.cpp src/patch_script.cpp)
target_include_directories(patch_compiler PUBLIC src)
if(WIN32)
    target_compile_definitions(patch_compiler PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
endif()
target_link_libraries(patch_compiler PRIVATE asmjit::asmtk Zydis)
target_include_directories(patch_compiler SYSTEM PRIVATE third_party/asmjit third_party/asmtk/src)
add_library(pugixml STATIC EXCLUDE_FROM_ALL third_party/pugixml/src/pugixml.cpp)
add_library(ct_import STATIC EXCLUDE_FROM_ALL src/ct_import.cpp)
target_link_libraries(ct_import PUBLIC patch_compiler PRIVATE pugixml)

if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(patch_compiler PRIVATE -Wall -Wextra -Wpedantic)
    target_compile_options(ct_import PRIVATE -Wall -Wextra -Wpedantic)
endif()
